apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: flz2rz0mr-nodejs
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-nodejs:09dd06f1c4ce6a8259d7700acebe48f00090a405@sha256:18d62270685fa2d3321f6a11adb5239f337b86c6b150f9d9b1a0717e4efc373a
          name: container-image
