apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: flz2rz0mr-nodejs
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-nodejs:fd849cc4a71b81501c3cf172f7b08d549ee46142@sha256:a4eb09b5369ef7da47fb09ebf0bcd530e1872d8b2f7598550d667d02b3c0e593
          name: container-image
