apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: flz2rz0mr-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: flz2rz0mr-nodejs 
  name: flz2rz0mr-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: flz2rz0mr-nodejs 
